### ISSUE TITLE
PrometheusReporter thread is not daemon

### ISSUE THREAD

**Issue by RobertoUa** [kamon-io/kamon-prometheus#30]
The thread should be daemon by default and users should be allowed to configure it.

**Comment by ivantopo** [comment]
Hey @RobertoUa, could you please explain a bit more what you mean by this?

**Comment by RobertoUa** [comment]
sorry, I meant thread. I have to call `sys.exit(0)` because app doesn't finish

**Comment by ivantopo** [comment]
Oh, now I see what you mean! So, this is not specific to the Prometheus module, it actually is part of Kamon core, we even have tests to ensure that this works this way! Instead of sys.exit, just make Kamon stop all reporters (that's either `Kamon.stopModules()` in Kamon 2.x or `Kamon.stopAllReporters()` in Kamon 1.x) and then the application will be able to stop without issues. 

The goal with that was to allow the reporters to push out the very last data they have before shutting down, which is specially important when running short-lived processes.

**Comment by RobertoUa** [comment]
I see, thanks! But maybe we can allow configuring it? I don't want to call `Kamon.stopAllReporters()` this seems wrong, and not obvious (I had to debug for a long time to find out which thread is daemon) every other dependency I can configure to make threads daemon.
